### ISSUE TITLE
Change manifest version 2 to 3

### ISSUE THREAD

**Issue by PratishShrivastava** [PratishShrivastava/google-meet-extension#1]
Change manifest version 2 to 3 

1. Go to manifest.json and change the version 2 to 3.
2.  change "browser_action" according to version 3 and than test in browser.

**Comment by saakshiraut28** [comment]
I would like to work on this issue.

**Comment by PratishShrivastava** [comment]
you can work on this

**Comment by PratishShrivastava** [comment]
Ok, thanks for contributing
