### ISSUE TITLE
Add folder 

### ISSUE THREAD

**Issue by PratishShrivastava** [PratishShrivastava/google-meet-extension#4]
Make proper folder and change the links.

**Comment by ignatiusobiorah** [comment]
what links are you referring to ?

**Comment by PratishShrivastava** [comment]
manifest.json links @ignatiusobiorah

**Comment by PratishShrivastava** [comment]
@ignatiusobiorah 

- [ ] Add two folder logo and public.
- [ ] Add pngs img into logo folder.
- [ ] Add pop.html file in public folder.
- [ ] Go to mainfest.json file and edit this

```
"action": {
        "default_popup": "pop.html",
        "default_icon": "logo.png"
  },
  "icons":{
      "128":"logo.png" 
  },
```

**To This**

```
"action": {
        "default_popup": "public/pop.html",
        "default_icon": "logo/logo.png"
  },
  "icons":{
      "128":"logo/logo.png" 
  },
```
