### ISSUE TITLE
update pop.html

### ISSUE THREAD

**Issue by PratishShrivastava** [PratishShrivastava/google-meet-extension#5]
update the html and css for extension.

**Comment by saakshiraut28** [comment]
I would also like to work on this one.

**Comment by PratishShrivastava** [comment]
If you are working on this provide a link of github also

**Comment by saakshiraut28** [comment]
Ok. It means I've to provide the link in the UI such that anyone who clicks on the link will be redirected to this repo.

**Comment by PratishShrivastava** [comment]
you can change the UI as you want, but make sure to give the github link

you can give heading, description, link for github, etc
